### ISSUE TITLE
Using deprecated constants as of 2024.1

### ISSUE THREAD

**Issue by bakerkj** [njobrien1006/hass_traeger#58] opened 2024-01-03 23:41 UTC
### System Health details

- Core: 2024.1.0
- Supervisor: 2023.12.0
- Operating: System 11.2
- Frontend: 20231208.2

### Checklist

- [ ] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/njobrien1006/hass_traeger/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Warnings from hass_traeger:

```
[homeassistant.const] TEMP_CELSIUS was used from traeger, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/njobrien1006/hass_traeger/issues
[homeassistant.const] TEMP_FAHRENHEIT was used from traeger, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report at https://github.com/njobrien1006/hass_traeger/issues
[homeassistant.components.climate.const] HVAC_MODE_COOL was used from traeger, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please create a bug report at https://github.com/njobrien1006/hass_traeger/issues
[homeassistant.components.climate.const] HVAC_MODE_HEAT was used from traeger, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/njobrien1006/hass_traeger/issues
[homeassistant.components.climate.const] HVAC_MODE_OFF was used from traeger, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/njobrien1006/hass_traeger/issues
[homeassistant.components.climate.const] SUPPORT_PRESET_MODE was used from traeger, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/njobrien1006/h
ass_traeger/issues
[homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from traeger, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/
njobrien1006/hass_traeger/issues

```

### Reproduction steps

1. Initially running Home Assistant `2023.12.4` with `hass_traeger` `2023.10.06.01`
2. Upgrade to Home Assistant `2024.1`
3. Observe `home-assistant.log`

**Comment by njobrien1006** [comment] 2024-01-04 18:40
Thank you for the report. I'm still on 2023.12.3 and didn't have any of those. 

It would appear they all came with 2023.12.4 on Dec-28-2023. If you'd like you can submit a pull for resolution against DEV branch otherwise, I'll evaluate as time permits.

**Comment by njobrien1006** [comment] 2024-01-05 22:13
Blog Refs:
[blog/2022/04/02/support-constants-deprecation](https://developers.home-assistant.io/blog/2022/04/02/support-constants-deprecation)
[blog/2022/05/03/constants-deprecations](https://developers.home-assistant.io/blog/2022/05/03/constants-deprecations)
[blog/2022/10/26/new-unit-enumerators](https://developers.home-assistant.io/blog/2022/10/26/new-unit-enumerators)

Code Examples:
[homeassistant/components/yolink/climate.py#L74-L79](https://github.com/mezz64/home-assistant/blob/997d4fbe5308b01d14ceabcfe089c2bc511473dd/homeassistant/components/yolink/climate.py#L74-L79)
[homeassistant/components/yolink/climate.py#L81-L85](https://github.com/mezz64/home-assistant/blob/997d4fbe5308b01d14ceabcfe089c2bc511473dd/homeassistant/components/yolink/climate.py#L81-L85)
[homeassistant/components/yolink/climate.py#L70](https://github.com/mezz64/home-assistant/blob/997d4fbe5308b01d14ceabcfe089c2bc511473dd/homeassistant/components/yolink/climate.py#L70)

**Comment by tmack8001** [comment] 2024-01-08 21:45
@njobrien1006 this looks to be a duplicate of https://github.com/njobrien1006/hass_traeger/issues/59 which it seems you are addressing already in a DEV branch build.

I didn't see that (this repo or that branch) originally  and added changes to my fork https://github.com/tmack8001/hass_traeger/tree/tmack/update-to-unitoftemp-forked feel free to take any or all the changes if you haven't already done similar yourself.

**Comment by njobrien1006** [comment] 2024-01-08 23:09
I wasn't certain how to classify it. I found it similar but different (as there are 3 different blog entries) and just left it open as the fix is currently in DEV-Branch (Beta-Released) awaiting testing.

**Closed** 2024-01-09 00:18 UTC
Labels: bug

**Comment by bakerkj** [comment] 2024-01-09 18:35
@njobrien1006 thanks for this fix!!
