### ISSUE TITLE
Temp format select between C and F

### ISSUE THREAD

**Issue by albiea** [njobrien1006/hass_traeger#84] opened 2024-12-24 20:34 UTC
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/njobrien1006/hass_traeger/issues?q=is%3Aissue+label%3A%22enhancement%22+).

### Is your feature request related to a problem? Please describe.

Temp readings (except for ambient) get selected for the current HA settings (ie C instead of F)

### Describe the solution you'd like

It would be great to have an option where a user can select what tempreture format they would like their smoker in (for example, I'm in Australia and we use Celcius but I use Farenheit when I cook on the smoker since most of the reciepes are in F)

### Describe alternatives you've considered

Have checked to see if i can select F but this would be a global change on the HA

### Additional context

![image](https://github.com/user-attachments/assets/00475c70-d055-4a3b-8622-1215b1218400)
Included a screenshot where ambient is coming through as F but the rest is reading as C

**Comment by doctorkb** [comment] 2024-12-24 20:38
Duplicate of #67

**Comment by njobrien1006** [comment] 2024-12-25 09:54
As elaborated in #67 this is not supported by HA Core.

**Comment by njobrien1006** [comment] 2024-12-25 09:55
As elaborated in #67 this is not supported by HA Core.

**Closed by njobrien1006** 2024-12-25 09:55 UTC
Labels: enhancement
